<a href="https://colab.research.google.com/github/sergeevgithub/deep_learning_2018-19/blob/master/%5Bhomework.adv%5Dpytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg"  width=400></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

In [0]:
from matplotlib import pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
import torch

### 1. Нахождение сложной производной

Найдите производную по x от функции 
$$\sin\left(\tan(x)\frac{x^2}{y} + \ln(e^{-x^2 + 3}+x^3y)\right)\tan(x^2e^{x^9})$$

При этом надо пользоваться встроенным в PyTorch autograd. Численное вычисление производной может не дать нужный результат.

In [0]:
def find_x_derivative(x, y):
    x = torch.Tensor([x]).requires_grad_() #x = torch.tensor([x], dtype=float, requires_grad=True)
    y = torch.Tensor([y]).requires_grad_() #y = torch.tensor([y], dtype=float, requires_grad=True)
    function = torch.sin(torch.tan(x) * x**2 / y + torch.log(torch.exp(-x**2 + 3) + x**3 * y)) * torch.tan(x**2 * torch.exp(x**9))
    function.backward()
    return round(x.grad.item(), 3) #округляем до 3 знаков после запятой

In [0]:
find_x_derivative(1, 21)

-9.021

In [0]:
x = torch.tensor([1], dtype=float, requires_grad=True)
y = torch.tensor([21], dtype=float, requires_grad=True)
tensor = torch.sin(torch.tan(x) * x**2 / y + torch.log(torch.exp(-x**2 + 3) + x**3 * y)) * torch.tan(x**2 * torch.exp(x**9))
tensor.backward()
print(x.grad)

tensor([-9.0207], dtype=torch.float64)


# 2. Нахождение косинусной близости

Вам даны две матрицы A и B. Необходимо посчитать косинусную близость между строчками матрицы A и столбцами матрицы B. Ответ - матрица чисел, где номер строки - номер строки из матрицы А, а номер столбца - номер столбца из В, от которых бралась косинусная близость.

Напомним, что косинусная близость двух векторов - косинус угла между ними. В n-мерном пространстве косинус угла между веткорами удобнее всего через скалярное произведение:
$$\cos(angle(x, y)) = \frac{x \cdot y}{\left\|x\right\| \left\|y\right\|}$$

(Наша операция очень похожа на умножение матриц)

In [0]:
def get_cos_sim(A, B):
    """
        A, B - torch float tensors
    """
    A_length_row = torch.FloatTensor(4, 1).zero_()
    B_length_column = torch.FloatTensor(1, 5).zero_()
    for i in range(len(A)):
      A_length_row[i] = ((A[i]**2).sum().sqrt())
    for i in range(B.shape[1]):
      B_length_column[0, i] = (B[:, i]**2).sum().sqrt()
    res = (A.mm(B)).div(A_length_row.mm(B_length_column))
    return res

In [6]:
A = torch.FloatTensor( [[1, -47, 25, -3], [10, 17, -15, 22], [-3, -7, 26, 36], [12, -27, -42, 0]])
B = torch.FloatTensor([[-50, -13, 1, 10, 1242], [21, 48, -13, -14, -20], [20, 15, 11, 43, 11], [11, 103, 147, 27, -8]])
answer = torch.mean(get_cos_sim(A, B))
print(round(answer.item(), 3)) # округляем

0.15


In [20]:
A = torch.FloatTensor( [[1, -47, 25, -3], [10, 17, -15, 22], [-3, -7, 26, 36], [12, -27, -42, 0]])
B = torch.FloatTensor([[-50, -13, 1, 10, 1242], [21, 48, -13, -14, -20], [20, 15, 11, 43, 11], [11, 103, 147, 27, -8]])
A_length_row = torch.FloatTensor(4, 1).zero_()
B_length_column = torch.FloatTensor(1, 5).zero_()
for i in range(len(A)):
  A_length_row[i] = ((A[i]**2).sum().sqrt())
for i in range(B.shape[1]):
  B_length_column[0, i] = (B[:, i]**2).sum().sqrt()
res = (A.mm(B)).div(A_length_row.mm(B_length_column))

round(torch.mean(res).item(), 3)

print(A_length_row)
print(B_length_column)

A_length_row.mm(B_length_column)


tensor([[53.3292],
        [33.1361],
        [45.0555],
        [51.3517]])
tensor([[  58.8388,  115.3560,  147.9865,   53.6097, 1242.2355]])


tensor([[ 3137.8223,  6151.8379,  7891.9956,  2858.9607, 66247.3828],
        [ 1949.6862,  3822.4448,  4903.6919,  1776.4154, 41162.8164],
        [ 2651.0112,  5197.4238,  6667.6084,  2415.4131, 55969.5703],
        [ 3021.4722,  5923.7285,  7599.3613,  2752.9507, 63790.9375]])

**Можно решить при помощи torch.norm:**

In [17]:
norm_a = torch.norm(A, dim=1)
norm_a

tensor([53.3292, 33.1361, 45.0555, 51.3517])

In [18]:
norm_b = torch.norm(B, dim=0)
norm_b

tensor([  58.8388,  115.3560,  147.9865,   53.6097, 1242.2355])

In [19]:
torch.mm(norm_a.view(4,1), norm_b.view(1,5))

tensor([[ 3137.8223,  6151.8379,  7891.9956,  2858.9607, 66247.3828],
        [ 1949.6862,  3822.4448,  4903.6919,  1776.4154, 41162.8164],
        [ 2651.0112,  5197.4238,  6667.6084,  2415.4131, 55969.5703],
        [ 3021.4722,  5923.7285,  7599.3613,  2752.9507, 63790.9375]])

# 3. Линейная регрессия

Раньше мы самостоятельно считали производные, чтобы находить веса линейной регрессии с помощью градиентного спуска. Теперь нам нужно использовать для этого PyTorch и его autograd. 

**Важно**: на самом деле .backward не обновляет содержимое матриц с производными (some_tensor.grad), а прибавляет к ним только что посчитаные значения проивзодных. Это значит, что вызвав .backward дважды, вы получите удвоенную производную. Так как мы обновляем веса в цикле и много раз вызываем .backward, то очень быстро мы получим мусор в some_tensor.grad, если не будем его каждый раз обнулять. Таким образом, в конц итериации после использования производных обнулите значения в матрице производных для всех нужных Вам переменных. Делается это вот так 
> some\_tensor.grad.data.zero_()

In [0]:
class LinearRegression:
    def get_loss(self, preds, y):
        """
            @param preds: предсказания модели
            @param y: истиные значения
            @return mse: значение MSE на переданных данных
        """
        # возьмите средний квадрат ошибки по всем выходным переменным
        # то есть сумму квадратов ошибки надо поделить на количество_элементов * количество_таргетов
        return #YOUR_CODE
    
    def init_weights(self, input_size, output_size):
        """
            Инициализирует параметры модели
            W - матрица размерности (input_size, output_size)
            инициализируется рандомными числами из
            uniform распределения (torch.rand())
            b - вектор размерности (1, output_size)
            инициализируется нулями
        """
        torch.manual_seed(0) #необходимо для воспроизводимости результатов
        self.W = torch.rand(input_size, output_size,  requires_grad=True)
        self.b = torch.zeros(1, output_size, requires_grad=True)

    def fit(self, X, y, num_epochs=1000, lr=0.001):
        """
            Обучение модели линейной регрессии методом градиентного спуска
            @param X: размерности (num_samples, input_shape)
            @param y: размерности (num_samples, output_shape)
            @param num_epochs: количество итераций градиентного спуска
            @param lr: шаг градиентного спуска
            @return metrics: вектор значений MSE на каждом шаге градиентного
            спуска.
        """
        self.init_weights(X.shape[1], y.shape[1])
        metrics = []
        for _ in range(num_epochs):
            preds = self.predict(X)
            # сделайте вычисления градиентов c помощью Pytorch и обновите веса
            # осторожнее, оберните вычитание градиента в 
#                 with torch.no_grad():
#                     #some code
            # иначе во время прибавления градиента к переменной создастся очень много нод в дереве операций
            # и ваши модели в будущем будут падать от нехватки памяти
            #YOUR_CODE
            #YOUR_CODE
            #YOUR_CODE
            #YOUR_CODE
            metrics.append(self.get_loss(preds, y).data)
        return metrics

    def predict(self, X):
        """
            Думаю, тут все понятно. Сделайте свои предсказания :)
        """
        return #YOUR_CODE

1. Сгенерируйте данные с помощью make_regression с параметрами n_targets=3, n_features=2, noise=10, random_state=42. 
2. Обучите модель линейной регрессии, оставив в fit параметры num_epochs и lr по умолчанию (обратите внимание, что перед обучением нужно привести данные к типу, использующимся в torch) 
2. Посчитайте среднее значение метрики MSE по всем итерациям цикла в fit (массив из значений MSE на каждой итерации возвращается из метода fit). Ответом, который необходимо сдать в систему, будет число, округленное до 3х знаков после запятой.

In [0]:
X, Y = # YOUR CODE HERE
X = # YOUR CODE HERE
Y = # YOUR CODE HERE
model = LinearRegression()
mse = model.fit(X, Y)

In [0]:
print(np.mean(mse))

Здесь предлагаем протестировать метод predict удобным вам образом.

In [0]:
#YOUR CODE